name: flutter_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  bloc: ^8.1.0
  connectivity_plus: ^2.3.9
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_datetime_picker: ^1.5.1
  flutter_picker: ^2.0.5
  flutter_screenutil: ^5.5.4
  font_awesome_flutter: ^10.2.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  google_nav_bar: ^5.0.6
  intl: ^0.17.0
  json_annotation: ^4.7.0
  timelines: ^0.1.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.2
  lint: ^1.10.0

flutter:

  uses-material-design: true

  assets:
    - assets/image_icons/icons8-cassette-100.png
    - assets/image_icons/icons8-confetti-100.png
    - assets/image_icons/icons8-disco-ball-100.png
    - assets/image_icons/icons8-laboratory-100.png
    - assets/image_icons/icons8-paint-palette-with-brush-100.png
    - assets/image_icons/icons8-rock-music-100.png
    - assets/image_icons/icons8-soccer-ball-100.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
          style: italic
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
          style: italic
